# Generated by Django 3.2.4 on 2021-07-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='days_spent',
            field=models.IntegerField(max_length=200),
        ),
    ]
