# Generated by Django 3.2.4 on 2021-07-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_attractions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='attraction',
            field=models.CharField(max_length=200),
        ),
    ]
