# Generated by Django 3.2.4 on 2021-07-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_airline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created',
        ),
        migrations.AddField(
            model_name='city',
            name='airlines',
            field=models.ManyToManyField(to='main_app.Airline'),
        ),
    ]
