# Generated by Django 3.2.4 on 2021-07-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_name_airline_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='rating',
            field=models.IntegerField(choices=[('1', '$'), ('2', '$$'), ('3', '$$$'), ('4', '$$$$'), ('5', '$$$$$')], default='1', max_length=1),
        ),
    ]
