# Generated by Django 3.2.4 on 2021-07-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_airline_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='rating',
            field=models.CharField(choices=[('A', '$'), ('B', '$$'), ('C', '$$$'), ('D', '$$$$'), ('E', '$$$$$')], default='A', max_length=1),
        ),
    ]
